### ISSUE TITLE
Config: Allow explicit type override in config.

### ISSUE THREAD

**Issue by juniwalk** [juniwalk/tessa#8]
There are types of assets that cannot be easily distinguished for types from file extension (url that don't have extension).

For ease of use and fast compiling, there should be an option to explicitly set asset type in the configuration.

Example:
```yaml
default:
    joinFiles: false
    assets:
        - %wwwDir%/css/style.css --type=js	# as cli param?
        - %wwwDir%/css/style.css?type=js	# as url query?

        # Potential issues
        - https://example.com/script.js --type=js	# should work well
        - https://example.com/script.js?type=js		# could be interpreted as part of the url
```

And the result
```php
$asset = new FileAsset($file, $type ?? null);
```

Leave room for future params extension if possible.
